### ISSUE TITLE
Calling forbidden letter data returns only data for u/neeeerrrdd despite specifying a u/ in the command.

### ISSUE THREAD

**Issue by HX56** [neeeerrd/h-bot10000#1]
Hi there,

Thanks for taking the time to update one of the greatest Reddit bots in existence.

I have attempted to use the forbidden letter counter on myself, of which I was returned only data for your account. I assume this was set up at some point in testing and forgotten about, if not, best of luck fixing this.

Thanks!
![image](https://github.com/neeeerrd/h-bot10000/assets/60305958/5a086ccc-c9f4-4db0-b252-1a408f1f5b61)

**Comment by neeeerrd** [comment]
yea i have absolutely no idea what is happening

**Comment by neeeerrd** [comment]
it has been fixed, albeit there is a new format for the forbidden letter checker, as now you should not use u/(username) and just type the username without the u/

**Comment by HX56** [comment]
Thank you for the quick fix, and con#ratulations on fi#urin# it out. From one developer to another, I know that wasn't easy.

Time to cut back on my use of the letter... whoops...

![image](https://github.com/neeeerrd/h-bot10000/assets/60305958/d3e2c6c0-64eb-4693-9140-6ffa31bd11af)
